### PR TITLE
Fixes xxxhdpi width and height which was switched

### PR DESCRIPTION
**Pull request by nicolascaorsi**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Good catch. Can you switch land as well? They are wrong too.

**Comment by nicolascaorsi** [comment]
Whoops... I missed that... Done.

**Comment by SamVerschueren** [comment]
Jeej :tada:! Much appreciated :beers: 

Should really add tests for this to check if all widths are greater than the heights in landscape and vice versa.

**Comment by SamVerschueren** [comment]
Sorry for the late released but it is now fixed in `0.1.1`.

**Pull request merged**
